import Scene from "./";
import Component from "./component";
import TransformComponent from "./core/transform_component";
import Mesh from "./core/mesh_component";
import Collider from "./core/collider_component";
export default class GameObject {
    name: string;
    private _scene;
    private _components;
    private _updateComponents;
    private _transform;
    private _parent;
    private _children;
    private instantiated;
    private _active;
    private _started;
    visible: boolean;
    constructor(name: string, scene: Scene);
    get transform(): TransformComponent;
    get mesh(): Mesh | null;
    get scene(): Scene;
    get parent(): GameObject | null;
    get children(): GameObject[];
    get active(): boolean;
    set active(active: boolean);
    get started(): boolean;
    set parent(parent: GameObject | null);
    add_child(child: GameObject): void;
    remove_child(child: GameObject): void;
    on_awake(): void;
    on_start(): void;
    on_update(dt: number): void;
    on_destroy(): void;
    destroy(): void;
    mouseEvent(type: number, button: number): void;
    inputEvent(type: number, key: string): void;
    addComponent<T extends Component>(component: T, needsUpdate?: boolean): T;
    getComponent<T extends Component>(type: new (...args: any[]) => T): T;
    removeComponent(component: Component): void;
    on_collision(other: Collider): void;
}
